// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sahibindenWebApi.Models;

#nullable disable

namespace sahibindenWebApi.Migrations
{
    [DbContext(typeof(DBsahibindenContext))]
    [Migration("20240813110348_AddRefreshTokenFields")]
    partial class AddRefreshTokenFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("sahibindenWebApi.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AdminAdres")
                        .HasColumnType("int");

                    b.Property<int?>("AdminId")
                        .HasColumnType("int");

                    b.Property<string>("AdminMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdminSifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdminSoyadi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("sahibindenWebApi.Models.Favori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int")
                        .HasColumnName("kullaniciId");

                    b.Property<int>("UrunId")
                        .HasColumnType("int")
                        .HasColumnName("urunId");

                    b.HasKey("Id");

                    b.ToTable("favori", (string)null);
                });

            modelBuilder.Entity("sahibindenWebApi.Models.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("kategoriAdi");

                    b.HasKey("Id")
                        .HasName("PK__kategori__3213E83FE9AC4163");

                    b.ToTable("kategori", (string)null);
                });

            modelBuilder.Entity("sahibindenWebApi.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("KullaniciAdres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("KullaniciMail")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("char(30)")
                        .IsFixedLength();

                    b.Property<string>("KullaniciSifre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KullaniciSoyadi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("KullaniciYetki")
                        .HasColumnType("int");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__kullanic__E011F77B073D8F2E");

                    b.ToTable("kullanici", (string)null);
                });

            modelBuilder.Entity("sahibindenWebApi.Models.Sepet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int")
                        .HasColumnName("kullaniciId");

                    b.Property<int>("UrunId")
                        .HasColumnType("int")
                        .HasColumnName("urunId");

                    b.HasKey("Id");

                    b.ToTable("sepet", (string)null);
                });

            modelBuilder.Entity("sahibindenWebApi.Models.Urunler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime")
                        .HasColumnName("eklenmeTarihi");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int")
                        .HasColumnName("kategoriId");

                    b.Property<string>("UrunAciklama")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("urunAciklama");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("urunAdi");

                    b.Property<string>("UrunDurum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("urunDurum");

                    b.Property<decimal>("UrunFiyat")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("urunFiyat");

                    b.Property<string>("UrunGorsel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("urunGorsel");

                    b.Property<int>("UrunStok")
                        .HasColumnType("int")
                        .HasColumnName("urunStok");

                    b.HasKey("Id")
                        .HasName("PK__urunler__3213E83F5DF9542D");

                    b.ToTable("urunler", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
